spring:
  application:
    name: provider-local

server:
  port: 60001

dubbo:
  registry:
    address: zookeeper://x.x.x.x:2181
    timeout: 10000

  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.vainycos.provider.service